name: blocklet

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-upload: false
          skip-deploy: true
          skip-release: true
          bundle-command: npm run bundle
          working-directory: ./client
          store-endpoint: ${{ secrets.STORE_ENDPOINT_DEV }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_DEV }}
          github-token: ${{ secrets.GIT_HUB_TOKEN }}
